name: Check if versions are consistent

on: 
  push:
    branches-ignore:
      - main

jobs:
  check-version-numbers:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python & Poetry Environment
        uses: ./.github/actions/prepare_poetry_env
      - name: Check Release
        run: ./scripts/build/check_release.sh "python3.8"
