name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check_setup_py:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Python & Poetry Environment
        uses: ./.github/actions/prepare_poetry_env
    - name: Setup poetry env
      run:  bash scripts/build/setup_poetry_env.sh "python3.8"

    - name: Run pytest
      run: poetry run pytest
